[project]
name = "software-supply-chain"
version = "0.1.0"
authors = [{ name = "Tory Clasen", email = "ToryClasen@gmail.com" }]
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "ruff>=0.12.2",
]
